import {TYPES,createGame,canPlace,place,remove,readiness,openFactory,tick,releaseBatch,nextOrder,moveBuilding,layoutIssues,refreshRoutes,restoreGame,dispatchTruck,LINKS} from './simulation.js';
import {createWorld,thumbnails} from './world.js';
const $=s=>document.querySelector(s), keys=Object.keys(TYPES), saveKey='cityfactory.syrup.v1';
const layout={roads:[0,6.5],utilities:[-8,-5],receiving:[-8,0],kitchen:[-2.5,0],quality:[-2.5,-5],bottling:[3.5,0],shipping:[9,0]};
let state=createGame(),selected=null,moving=null,inspected=null,rot=0,position={x:0,z:0},world,toastTimer,simulationTime=0;
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3800);}
function save(){try{localStorage.setItem(saveKey,JSON.stringify({version:1,state}));}catch{ /* A private browser can still play without persistence. */ }}
function restore(){try{const raw=JSON.parse(localStorage.getItem(saveKey));if(!raw?.state)return;state=restoreGame(raw.state);if(raw.state.schema!==2)toast('Your layout is saved. A new 300-carton material-flow challenge is ready.');}catch{toast('The saved game could not be validated. Your previous save remains in the backup.');}}
const seconds=n=>`${Math.round(n)}s`;
function currentMessage(){
 if(state.phase==='build')return state.message;
 if(state.phase==='complete')return `300 cartons delivered in ${seconds(state.time)}. Try the same order with a shorter route.`;
 if(state.phase==='receiving')return state.supply.status==='approaching'?'Ingredients and packaging are arriving by truck.':'Receiving is unloading 300 ingredient units and 300 packaging kits.';
 if(state.phase==='transferring')return 'Ingredients are travelling to the kitchen. Packaging travels directly to Bottling.';
 if(state.phase==='mixing')return 'Mixing 100 ingredient units into 100 syrup units. Machine time: 12 seconds.';
 if(state.phase==='bottling')return state.stock.bottleSyrup===0?'Bottling is waiting for syrup to arrive. Shorter transfer paths reduce this wait.':state.stock.bottlePacks===0?'Bottling is waiting for packaging from Receiving.':'Bottling uses 1 syrup unit + 1 packaging kit per carton. Rate: 10 cartons/second.';
 if(state.phase==='awaitingQuality')return '100 cartons are held for quality release. The customer truck cannot load them yet.';
 return 'All batches released. Cartons are travelling to Shipping and loading into the truck.';
}
function updateUI(){
 const build=state.phase==='build',missing=readiness(state),issues=build?layoutIssues(state):[];
 $('#money').textContent=state.money.toLocaleString('en-US');$('#mode').textContent=build?'Plan the flow':state.phase==='complete'?'Order delivered':state.paused?'Factory paused':'Order: 300 cartons';
 $('#open').disabled=!build||missing.length>0||issues.length>0;$('#open').title=issues[0]||'';$('#open').innerHTML=build?'Open factory <span>↗</span>':'Factory open <span>✓</span>';
 $('#built-count').textContent=`${7-missing.length} / 7`;$('#build-bar').style.width=`${(7-missing.length)/7*100}%`;
 $('#mission-title').innerHTML=build?'Build a smarter<br>material flow.':state.phase==='complete'?'Order delivered.<br>Can you beat it?':state.phase==='awaitingQuality'?'Check it.<br>Then release it.':'From ingredients<br>to delivery.';
 $('#mission-copy').textContent=issues[0]||currentMessage();$('#mission-count').textContent=build?'01 / 03':state.phase==='complete'?'03 / 03':'02 / 03';
 $('#build-progress').hidden=!build;$('#order-progress').hidden=build;$('#quick-build').hidden=!build||!missing.length;$('#release').hidden=state.phase!=='awaitingQuality';$('#next-order').hidden=state.phase!=='complete';
 $('#batch-id').textContent=`Batch ${state.batchNumber} of 3 · ${state.batchId}`;$('#carton-count').textContent=state.delivered;$('#production-bar').style.width=`${state.delivered/3}%`;
 $('#status-line').textContent=build?(issues[0]||`${7-missing.length} / 7 essentials · Order 300 · Batch 100 · Truck 200`):`${state.totalPacked} packed · ${state.stock.ready} ready at Shipping · ${state.truck.load} on truck · ${state.delivered} delivered`;
 $('#learning-tip').textContent=build?'Short routes. Clear docks. Same machine speeds.':'Cartons count as delivered when the truck leaves.';
 $('#pause').textContent=state.paused?'▶':'Ⅱ';$('#pause').setAttribute('aria-label',state.paused?'Resume simulation':'Pause simulation');$('#speed').textContent=`${state.speed}×`;
 $('#flow-stats').hidden=build;$('#elapsed-time').textContent=seconds(state.time);$('#truck-wait').textContent=seconds(state.truckWait);$('#trip-count').textContent=state.trips;
 $('#truck-status').textContent=build?'Truck capacity: 200 cartons':`Truck: ${state.truck.status} · ${state.truck.load} / 200 cartons`;
 $('#dispatch').hidden=build||state.phase==='complete';$('#dispatch').disabled=!['waiting','loading'].includes(state.truck.status)||!state.truck.load;$('#dispatch').textContent=`Send ${state.truck.load} cartons now →`;
 $('#retry').hidden=build||state.phase==='complete';$('#retry').disabled=!state.paused;
 $('#best-time').hidden=!state.best;$('#best-time').textContent=state.best?`Best: ${seconds(state.best.time)} · Previous: ${seconds(state.previous.time)}`:'';
 $('#inventory').textContent=`Receiving: ${state.stock.raw} ingredients · ${state.stock.packs} kits. Kitchen: ${state.stock.kitchenRaw} ingredients. Bottling: ${state.stock.bottleSyrup} syrup · ${state.stock.bottlePacks} kits · ${state.stock.held} held cartons. Shipping: ${state.stock.ready} released cartons. In transit: ${state.transfers.reduce((n,t)=>n+t.amount,0)} units.`;
 $('#remove').hidden=!build;$('#move-module').disabled=!build&&!state.paused;
 for(const key of keys){const exists=!missing.includes(key);$(`[data-check="${key}"]`).classList.toggle('done',exists);const btn=$(`[data-tool="${key}"]`);btn.classList.toggle('placed',exists);btn.classList.toggle('selected',selected===key);btn.setAttribute('aria-pressed',String(selected===key));btn.querySelector('.tool-cost').textContent=exists?'Placed ✓':`${(TYPES[key].cost/1000).toFixed(0)}k credits`;}
 const seq=['receiving','transferring','mixing','bottling','awaitingQuality','dispatching'];const active=seq.indexOf(state.phase);$('#stages').innerHTML=seq.map((p,i)=>`<span class="stage ${i===active?'current':''}">${['Receive','Move','Mix','Pack','Check','Ship'][i]}</span>`).join('');
}
function routeSummary(draft){return LINKS.filter(([k])=>draft.routes[k]).map(([k,,,label])=>`${label}: ${seconds(draft.routes[k].duration)}`).join(' · ');}
function updateRoutes(){refreshRoutes(state);$('#route-summary').textContent=routeSummary(state)||'Place production modules to preview transfer times.';}
function sync(){updateRoutes();world.sync(state);updateUI();save();}
function clearSelection(){selected=null;moving=null;world.setGhost(null);world.previewRoutes(state);$('#placement-tip').hidden=true;updateUI();}
function candidate(){const draft=structuredClone(state);const result=moving?moveBuilding(draft,moving,position.x,position.z,rot):place(draft,selected,position.x,position.z,rot);if(result.ok)refreshRoutes(draft);return {draft,result};}
function showGhost(){if(!selected)return;const def=TYPES[selected];if(selected==='roads'){position={x:0,z:6.5};rot=0;}const {draft,result}=candidate();world.setGhost(selected,position.x,position.z,rot,result.ok,def.w,def.d);$('#placement-name').textContent=`${moving?'Move ':''}${def.name}`;$('#placement-feedback').textContent=result.ok?routeSummary(draft):result.reason;$('#place-suggested').disabled=!result.ok;$('#place-suggested').title=result.reason||'Place module';world.previewRoutes(result.ok?draft:state);}
function select(type){const existing=state.buildings.find(b=>b.type===type);if(existing){clearSelection();inspect(existing.id);return;}if(state.phase!=='build')return;selected=type;rot=0;position={x:layout[type][0],z:layout[type][1]};$('#placement-tip').hidden=false;$('#inspector').hidden=true;showGhost();updateUI();world.canvas.focus({preventScroll:true});}
function placeSelected(){if(!selected)return;const type=selected,result=moving?moveBuilding(state,moving,position.x,position.z,rot):place(state,type,position.x,position.z,rot);if(!result.ok){toast(result.reason);return;}clearSelection();sync();toast(`${TYPES[type].name} is in. ${TYPES[type].lesson}`);}
function inspect(id){const b=state.buildings.find(b=>b.id===id);if(!b)return;inspected=id;const def=TYPES[b.type];$('#inspect-title').textContent=def.name;$('#inspect-description').textContent=def.description;$('#inspect-lesson').textContent=def.lesson;$('#inspect-route').textContent=LINKS.filter(([,a,c])=>a===b.type||c===b.type).map(([k,,,label])=>`${label}: ${state.routes[k]?seconds(state.routes[k].duration):'not connected'}`).join(' · ');$('#inspector').hidden=false;$('#remove').hidden=state.phase!=='build';}
function starterLayout(){// Keep the player's existing modules; find space for only the missing ones.
 const draft=structuredClone(state);for(const type of readiness(draft)){let [x,z]=layout[type];let result=place(draft,type,x,z);if(!result.ok&&type!=='roads'){outer:for(let row=-6;row<=3;row+=.5)for(let col=-10;col<=10;col+=.5)for(const r of [0,1]){result=place(draft,type,col,row,r);if(result.ok)break outer;}}if(!result.ok){toast('The remaining modules need more room. Remove or reposition a module first.');return;}}state=draft;clearSelection();sync();toast('Your starter factory is ready. Explore each module, then open the factory.');}
function showDialog(id){clearSelection();$(id).showModal();}
try{
 try{const old=localStorage.getItem(saveKey);if(old&&!localStorage.getItem(saveKey+'.before-flow'))localStorage.setItem(saveKey+'.before-flow',old);}catch{}
 restore();world=createWorld($('#scene'));const icons=thumbnails();
 $('#tools').innerHTML=keys.map((key,i)=>`<button class="tool" data-tool="${key}" aria-label="${TYPES[key].name}: ${TYPES[key].cost.toLocaleString()} credits" aria-pressed="false"><kbd>${i+1}</kbd><img alt="" src="${icons[key]}"><span class="tool-name">${key==='kitchen'?'Syrup Kitchen':TYPES[key].name}</span><span class="tool-cost"></span></button>`).join('');
 $('#checklist').innerHTML=keys.map(key=>`<div class="check-item" data-check="${key}">${key==='kitchen'?'Syrup Kitchen':TYPES[key].name}</div>`).join('');
 $('#tools').addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b)select(b.dataset.tool);});$('#labels').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b){clearSelection();inspect(b.dataset.id);}});
 let down=null;world.canvas.addEventListener('pointerdown',e=>{if(e.button===0)down={x:e.clientX,y:e.clientY};});world.canvas.addEventListener('pointermove',e=>{if(!selected||e.buttons===2)return;const p=world.pick(e.clientX,e.clientY);position={x:p.x,z:p.z};showGhost();});world.canvas.addEventListener('pointerup',e=>{if(e.button!==0||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;down=null;const p=world.pick(e.clientX,e.clientY);if(selected){position={x:p.x,z:p.z};showGhost();placeSelected();}else if(p.id)inspect(p.id);else $('#inspector').hidden=true;});world.canvas.addEventListener('contextmenu',e=>e.preventDefault());
 document.addEventListener('keydown',e=>{if($('dialog[open]'))return;const nativeButton=e.target.closest('button');if(e.key==='Escape'){clearSelection();$('#inspector').hidden=true;return;}if(/^[1-7]$/.test(e.key)){select(keys[+e.key-1]);return;}if(e.code==='Space'&&e.target===world.canvas){e.preventDefault();state.paused=!state.paused;updateUI();save();return;}if(!selected)return;if(e.key.toLowerCase()==='r'){rot=1-rot;showGhost();return;}if(e.key==='Enter'&&!nativeButton){e.preventDefault();placeSelected();return;}if(e.key.startsWith('Arrow')){e.preventDefault();position.x+=e.key==='ArrowRight'?.5:e.key==='ArrowLeft'?-.5:0;position.z+=e.key==='ArrowDown'?.5:e.key==='ArrowUp'?-.5:0;showGhost();}});
 $('#collapse-mission').onclick=()=>{const collapsed=$('#mission').classList.toggle('collapsed');$('#collapse-mission').textContent=collapsed?'+':'−';$('#collapse-mission').setAttribute('aria-expanded',String(!collapsed));$('#collapse-mission').setAttribute('aria-label',collapsed?'Expand mission':'Collapse mission');};$('#move-module').onclick=()=>{const b=state.buildings.find(b=>b.id===inspected);if(!b)return;selected=b.type;moving=b.id;rot=b.rot;position={x:b.x,z:b.z};$('#inspector').hidden=true;$('#placement-tip').hidden=false;showGhost();world.canvas.focus();};$('#dispatch').onclick=()=>{const r=dispatchTruck(state);if(r.ok)sync();else toast(r.reason);};$('#retry').onclick=()=>showDialog('#retry-dialog');$('#confirm-retry').onclick=()=>{const r=nextOrder(state);if(r.ok){$('#retry-dialog').close();clearSelection();sync();}else toast(r.reason);};$('#place-suggested').onclick=placeSelected;$('#quick-build').onclick=starterLayout;$('#close-inspector').onclick=()=>$('#inspector').hidden=true;$('#remove').onclick=()=>{const result=remove(state,inspected);if(result.ok){$('#inspector').hidden=true;sync();}else toast(result.reason);};$('#open').onclick=()=>{const result=openFactory(state);if(result.ok){clearSelection();$('#inspector').hidden=true;sync();toast('The gates are open. Your first ingredients are on their way.');}else toast(result.reason);};$('#release').onclick=()=>{$('#review-batch').textContent=state.batchId;showDialog('#release-dialog');};$('#confirm-release').onclick=()=>{const r=releaseBatch(state);if(r.ok){$('#release-dialog').close();sync();toast('100 cartons released and on their way to Shipping.');}else toast(r.reason);};$('#next-order').onclick=()=>{const r=nextOrder(state);if(r.ok)sync();else toast(r.reason);};$('#pause').onclick=()=>{state.paused=!state.paused;updateUI();save();};$('#speed').onclick=()=>{state.speed=state.speed===1?2:1;updateUI();save();};$('#home').onclick=()=>world.home();$('#zoom-in').onclick=()=>world.zoom(.88);$('#zoom-out').onclick=()=>world.zoom(1.13);$('#flow').onclick=()=>{const on=world.toggleFlow();$('#flow').classList.toggle('active',on);$('#flow').setAttribute('aria-pressed',String(on));};$('#help').onclick=()=>showDialog('#help-dialog');$('#reset').onclick=()=>showDialog('#reset-dialog');$('#confirm-reset').onclick=()=>{state=createGame();$('#reset-dialog').close();$('#inspector').hidden=true;clearSelection();sync();world.home();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 sync();if(innerWidth<600)$('#collapse-mission').click();let last=performance.now(),uiTime=0,saveTime=0;
 function frame(now){requestAnimationFrame(frame);const dt=Math.max(0,Math.min((now-last)/1000,.1));last=now;const phase=state.phase;if(!$('dialog[open]'))tick(state,dt);if(!state.paused&&!reducedMotion&&!$('dialog[open]'))simulationTime+=dt*state.speed;world.render(state,simulationTime);uiTime+=dt;saveTime+=dt;if(uiTime>.15){updateUI();uiTime=0;const mins=Math.floor(simulationTime*.9);$('#clock').textContent=`DAY 01 · ${String(8+Math.floor(mins/60)).padStart(2,'0')}:${String(mins%60).padStart(2,'0')}`;}if(phase!==state.phase){if(['awaitingQuality','complete'].includes(state.phase))$('#mission').scrollTop=0;save();if(state.phase==='awaitingQuality')toast('Batch packed. Review and release these 100 cartons.');if(state.phase==='complete')toast('First order delivered. You built a working manufacturing system!');}if(saveTime>3){save();saveTime=0;}}
 requestAnimationFrame(frame);$('#loading').classList.add('done');window.addEventListener('pagehide',save);
 // Inspection hook exposes a read-only snapshot for local smoke checks.
 window.cityFactory={snapshot:()=>structuredClone(state)};
}catch(error){console.error(error);$('#loading').innerHTML='<h2>This little world could not start.</h2><p>Check that WebGL is enabled and reload the page.</p>';}
